In [2]:
import os
os.environ["OPENAI_API_KEY"] = "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"

import warnings
warnings.simplefilter('ignore')

import numpy as np
from langchain_openai import OpenAIEmbeddings
embedding = OpenAIEmbeddings()

In [13]:
# 埋め込みベクトルの作成
texts=["Attention Is All You Need"]
vector = np.array(embedding.embed_documents(texts))#,dtype=np.float32)

In [8]:
# 埋め込みベクトルの型を作成
vector[0].dtype

dtype('float64')

In [9]:
# 埋め込みベクトルの表示
vector[0]

array([-0.01761251,  0.02826253,  0.04649392, ..., -0.01259049,
       -0.00670461, -0.0188245 ])

In [10]:
# 埋め込みベクトルの型変換
vector_f32 = vector[0].astype(np.float32)
vector_f16 = vector[0].astype(np.float16)

In [14]:
# 埋め込みベクトルの表示
vector_f32

array([-0.01761251,  0.02826253,  0.04649393, ..., -0.01259049,
       -0.00670461, -0.0188245 ], dtype=float32)

In [15]:
# 埋め込みベクトルの表示
vector_f16

array([-0.01761 ,  0.02826 ,  0.0465  , ..., -0.01259 , -0.006706,
       -0.01883 ], dtype=float16)

In [29]:
# さらに精度を落とす
vector_4_decimal = np.around(vector[0], decimals=4).astype(np.float16)

In [30]:
vector_4_decimal

array([-0.0176,  0.0283,  0.0465, ..., -0.0126, -0.0067, -0.0188],
      dtype=float16)

In [31]:
# さらに精度を落とす
vector_3_decimal = np.around(vector[0], decimals=3).astype(np.float16)

In [32]:
vector_3_decimal

array([-0.018,  0.028,  0.046, ..., -0.013, -0.007, -0.019], dtype=float16)